(()=>{'use strict';
const root=document.documentElement;root.classList.add('js');
const screens=[...document.querySelectorAll('.story-screen')];
const header=document.querySelector('.header'),menu=document.querySelector('#chapter-menu'),menuButton=document.querySelector('.menu-button');
const previous=document.querySelector('#previous'),next=document.querySelector('#next'),counter=document.querySelector('#screen-count'),fullscreen=document.querySelector('#fullscreen'),motion=document.querySelector('#motion');
const preference=matchMedia('(prefers-reduced-motion: reduce)');let reduced=preference.matches,stops=[],current=0,queued=false,lastStep=null;
function setMotion(){root.classList.toggle('reduced-motion',reduced);motion.setAttribute('aria-pressed',String(reduced));motion.setAttribute('aria-label',reduced?'Activer les animations':'Réduire les animations');motion.firstElementChild.textContent=reduced?'▷':'Ⅱ';window.dispatchEvent(new CustomEvent('motionchange',{detail:reduced}));}
motion.addEventListener('click',()=>{reduced=!reduced;setMotion();});preference.addEventListener('change',e=>{reduced=e.matches;setMotion();});setMotion();
function closeMenu(){menu.hidden=true;menuButton.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open');}
menuButton.addEventListener('click',()=>{const open=menu.hidden;menu.hidden=!open;menuButton.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open);if(open)menu.querySelector('a').focus();});
function buildStops(){const inset=header.offsetHeight,available=Math.max(120,innerHeight-inset),max=Math.max(0,root.scrollHeight-innerHeight);stops=[];
 function add(screen,top){top=Math.max(0,Math.min(max,top));if(!stops.length||top-stops[stops.length-1].top>8)stops.push({screen,top});}
 screens.forEach(screen=>{const rect=screen.getBoundingClientRect(),base=rect.top+scrollY-inset;add(screen,base);const extra=Math.max(0,screen.offsetHeight-available);let offset=0;while(extra-offset>8){offset=Math.min(extra,offset+available*.82);add(screen,base+offset);}});update();}
function update(){queued=false;if(!stops.length)return;let index=0,best=Infinity;stops.forEach((stop,i)=>{const d=Math.abs(stop.top-scrollY);if(d<best){best=d;index=i;}});current=index;paint();}
function paint(){const stop=stops[current];if(!stop)return;previous.disabled=current===0;next.disabled=current===stops.length-1;counter.textContent=`${String(current+1).padStart(2,'0')} / ${String(stops.length).padStart(2,'0')}`;const chapter=stop.screen.closest('.chapter');menu.querySelectorAll('a').forEach(a=>{if(a.getAttribute('href')==='#'+chapter.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});const step=stop.screen.dataset.step;root.dataset.presentationStep=step;root.classList.toggle('final-background',step==='20');document.querySelector('.hero-art').style.opacity=String(step==='20'?.75:Math.max(0,.75-scrollY/innerHeight*.75));if(step!==lastStep){lastStep=step;window.dispatchEvent(new CustomEvent('presentation-step',{detail:{step,chapter:chapter.id}}));}}
function go(index){current=Math.max(0,Math.min(stops.length-1,index));closeMenu();paint();window.scrollTo({top:stops[current].top,behavior:'instant'});}
previous.addEventListener('click',()=>go(current-1));next.addEventListener('click',()=>go(current+1));
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const target=document.getElementById(a.getAttribute('href').slice(1));if(!target)return;const screen=target.matches('.story-screen')?target:target.querySelector('.story-screen')||target.closest('.story-screen');const index=stops.findIndex(s=>s.screen===screen);if(index>=0){e.preventDefault();go(index);}}));
async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(root.requestFullscreen)await root.requestFullscreen();}catch(e){fullscreen.title='Le navigateur ne permet pas le plein écran ici.';}}
fullscreen.addEventListener('click',toggleFullscreen);if(!root.requestFullscreen)fullscreen.hidden=true;
document.addEventListener('fullscreenchange',()=>{fullscreen.setAttribute('aria-label',document.fullscreenElement?'Quitter le plein écran':'Passer en plein écran');buildStops();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!menu.hidden){closeMenu();menuButton.focus();return;}if(!menu.hidden){if(e.key==='Tab'){const items=[menuButton,...menu.querySelectorAll('a')],first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}if(e.altKey||e.ctrlKey||e.metaKey||e.target.closest('input,textarea,select,[contenteditable="true"]'))return;if(e.key===' '&&e.target.closest('button,a'))return;
 let destination;if(['ArrowRight','ArrowDown','PageDown'].includes(e.key)||(e.key===' '&&!e.shiftKey))destination=current+1;else if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)||(e.key===' '&&e.shiftKey))destination=current-1;else if(e.key==='Home')destination=0;else if(e.key==='End')destination=stops.length-1;else if(e.key.toLowerCase()==='f'){if(!e.repeat)toggleFullscreen();e.preventDefault();return;}if(destination!==undefined){e.preventDefault();if(!e.repeat)go(destination);}});
const reveal=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');reveal.unobserve(entry.target);}});},{threshold:.07});document.querySelectorAll('.reveal').forEach(el=>reveal.observe(el));
addEventListener('scroll',()=>{if(!queued){queued=true;requestAnimationFrame(update);}},{passive:true});let resizeTimer;addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(buildStops,100);});buildStops();if(document.fonts)document.fonts.ready.then(buildStops);addEventListener('load',buildStops);
})();
